"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import {
  Sparkles,
  Loader2,
  Save,
  Download,
  RotateCcw,
  Send,
  FileText,
  MessageSquare,
  X,
  Bold,
  Italic,
  List,
  ListOrdered,
  Heading1,
  Heading2,
  Heading3,
  Undo2,
  Redo2,
} from "lucide-react";
import { toast } from "sonner";
import { useEditor, EditorContent } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import Placeholder from "@tiptap/extension-placeholder";
import Typography from "@tiptap/extension-typography";
import { useRFPStore } from "@/store/useRFPStore";
import { useRFPStream } from "@/hooks/useRFPStream";
import { markdownToHtml } from "@/lib/markdown";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";

interface RFPTechnicalEditorProps {
  rfpId: string;
}

export function RFPTechnicalEditor({ rfpId }: RFPTechnicalEditorProps) {
  const product = useRFPStore((s) => s.product);
  const projectName = useRFPStore((s) => s.projectName);
  const projectDescription = useRFPStore((s) => s.projectDescription);
  const technicalContent = useRFPStore((s) => s.technicalContent);
  const streamingContent = useRFPStore((s) => s.streamingContent);
  const phase = useRFPStore((s) => s.phase);
  const appendChunk = useRFPStore((s) => s.appendChunk);
  const clearStreamingContent = useRFPStore((s) => s.clearStreamingContent);
  const setTechnicalContent = useRFPStore((s) => s.setTechnicalContent);
  const setPhase = useRFPStore((s) => s.setPhase);
  const setErrorMessage = useRFPStore((s) => s.setErrorMessage);

  const [adjustContext, setAdjustContext] = useState("");
  const [promptHistory, setPromptHistory] = useState<
    { role: "user" | "system"; text: string }[]
  >([]);
  const [wordCount, setWordCount] = useState(0);
  const editorScrollRef = useRef<HTMLDivElement>(null);
  const panelScrollRef = useRef<HTMLDivElement>(null);
  const prevStreamRef = useRef(streamingContent);
  const storeUpdateRef = useRef(false);
  const hasAutoGenerated = useRef(false);

  const editor = useEditor({
    immediatelyRender: false,
    extensions: [
      StarterKit.configure({
        heading: { levels: [1, 2, 3] },
      }),
      Placeholder.configure({
        placeholder: "Technical content will appear here...",
      }),
      Typography,
    ],
    editable: true,
    editorProps: {
      attributes: {
        class:
          "outline-none min-h-full prose prose-sm prose-neutral max-w-none dark:prose-invert prose-headings:font-semibold prose-h1:text-xl prose-h2:text-base prose-h3:text-sm prose-p:leading-relaxed prose-p:text-[13.5px] prose-li:text-[13.5px] prose-ul:my-2 prose-ol:my-2 prose-li:my-0.5",
      },
    },
    onUpdate: ({ editor: ed }) => {
      if (storeUpdateRef.current) return;
      const html = ed.getHTML();
      setTechnicalContent(html);
      const text = ed.getText();
      setWordCount(text.trim().split(/\s+/).filter(Boolean).length);
    },
  });

  const stream = useRFPStream({
    onChunk: (chunk) => {
      appendChunk(chunk);
    },
    onComplete: (full) => {
      const html = markdownToHtml(full);
      setTechnicalContent(html);
      storeUpdateRef.current = true;
      editor?.commands.setContent(html);
      storeUpdateRef.current = false;
      const text = editor?.getText() || "";
      setWordCount(text.trim().split(/\s+/).filter(Boolean).length);
      setPhase("completed");
      setPromptHistory((prev) => [
        ...prev,
        { role: "system", text: "Content updated successfully." },
      ]);
      toast.success("Generation complete");
    },
    onError: (msg) => {
      setPhase("error");
      setErrorMessage(msg);
      setPromptHistory((prev) => [
        ...prev,
        { role: "system", text: `Error: ${msg}` },
      ]);
    },
  });

  const isStreaming = stream.isStreaming;

  useEffect(() => {
    if (!editor) return;
    editor.setEditable(!isStreaming);
  }, [editor, isStreaming]);

  useEffect(() => {
    if (isStreaming && prevStreamRef.current !== streamingContent) {
      if (editorScrollRef.current) {
        editorScrollRef.current.scrollTop =
          editorScrollRef.current.scrollHeight;
      }
    }
    prevStreamRef.current = streamingContent;
  }, [streamingContent, isStreaming]);

  useEffect(() => {
    if (panelScrollRef.current) {
      panelScrollRef.current.scrollTop = panelScrollRef.current.scrollHeight;
    }
  }, [promptHistory]);

  const handleGenerate = useCallback(() => {
    if (!product.trim()) {
      toast.error("Product name required");
      return;
    }
    clearStreamingContent();
    editor?.commands.clearContent();
    setPhase("generating");
    setPromptHistory((prev) => [
      ...prev,
      { role: "user", text: `Generate Chapter 3 for "${product}"` },
    ]);
    stream.generate(product, { projectName, projectDescription });
  }, [product, projectName, projectDescription, stream, setPhase, clearStreamingContent, editor]);

  const handleAdjust = useCallback(() => {
    if (!adjustContext.trim()) {
      toast.error("Enter adjustment instructions");
      return;
    }
    if (!technicalContent.trim()) {
      toast.error("No content to adjust. Generate first.");
      return;
    }
    const ctx = adjustContext;
    const plainContent = editor?.getText() || technicalContent;
    clearStreamingContent();
    editor?.commands.clearContent();
    setPhase("adjusting");
    setPromptHistory((prev) => [...prev, { role: "user", text: ctx }]);
    stream.adjust(product, plainContent, ctx);
    setAdjustContext("");
  }, [adjustContext, technicalContent, product, stream, setPhase, editor, clearStreamingContent]);

  const handleSave = useCallback(() => {
    toast.success("Changes saved successfully");
  }, []);

  const handleExport = useCallback(() => {
    const text = editor?.getText() || "";
    if (!text.trim()) {
      toast.error("No content to export");
      return;
    }
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `RFP_Chapter3_Technical_${rfpId}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Exported successfully");
  }, [editor, rfpId]);

  const hasContent = technicalContent.trim().length > 0;

  useEffect(() => {
    if (product && technicalContent.trim().length === 0 && !hasAutoGenerated.current && !isStreaming) {
      hasAutoGenerated.current = true;
      handleGenerate();
    }
  }, [product, technicalContent, isStreaming, handleGenerate]);

  return (
    <div className="flex flex-col overflow-hidden" style={{ height: "calc(100dvh - 3.5rem)" }}>
      {/* Toolbar */}
      <div className="flex shrink-0 items-center justify-between border-b bg-background/95 px-4 py-2 backdrop-blur-sm">
        <div className="flex items-center gap-2">
          <div className="flex size-7 items-center justify-center rounded-md bg-primary/10">
            <FileText className="size-3.5 text-primary" />
          </div>
          <div className="flex flex-col">
            <span className="text-sm font-semibold leading-none tracking-tight">
              {product || rfpId}
            </span>
            {projectName && (
              <span className="text-[11px] leading-tight text-muted-foreground">
                {projectName}
              </span>
            )}
          </div>
          {isStreaming && (
            <Badge variant="secondary" className="gap-1 text-[11px]">
              <Loader2 className="size-3 animate-spin" />
              {phase === "generating" ? "Generating" : "Adjusting"}
            </Badge>
          )}
          {phase === "completed" && !isStreaming && (
            <Badge variant="secondary" className="text-[11px]">
              Complete
            </Badge>
          )}
          {phase === "error" && (
            <Badge variant="destructive" className="text-[11px]">
              Error
            </Badge>
          )}
        </div>

        <div className="flex items-center gap-1.5">
          {!hasContent && (
            <Button
              variant="default"
              size="sm"
              onClick={handleGenerate}
              disabled={isStreaming}
            >
              {isStreaming ? (
                <Loader2 className="animate-spin" />
              ) : (
                <Sparkles />
              )}
              Generate
            </Button>
          )}
          {hasContent && (
            <Button
              variant="ghost"
              size="xs"
              onClick={handleGenerate}
              disabled={isStreaming}
            >
              <RotateCcw className="size-3" />
              Redo
            </Button>
          )}
          <Button variant="outline" size="xs" onClick={handleSave}>
            <Save className="size-3" />
            Save
          </Button>
          <Button variant="ghost" size="xs" onClick={handleExport}>
            <Download className="size-3" />
            Export
          </Button>
        </div>
      </div>

      {/* Split Pane Body */}
      <div className="flex min-h-0 flex-1 overflow-hidden">
        {/* Left: Editor (scrollable) */}
        <div className="flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden border-r">
          {isStreaming ? (
            <div
              ref={editorScrollRef}
              className="min-h-0 flex-1 overflow-y-auto p-6"
            >
              <div className="mx-auto max-w-3xl">
                <div className="mb-3 flex items-center gap-2">
                  <Loader2 className="size-3.5 animate-spin text-muted-foreground" />
                  <span className="text-xs text-muted-foreground">
                    {phase === "generating"
                      ? "Generating technical proposal..."
                      : "Adjusting content..."}
                  </span>
                </div>
                <div
                  className="prose prose-sm prose-neutral max-w-none dark:prose-invert text-[13px]"
                  dangerouslySetInnerHTML={{
                    __html: markdownToHtml(streamingContent) + '<span class="ml-0.5 inline-block h-4 w-[2px] animate-pulse bg-foreground" />',
                  }}
                />
              </div>
            </div>
          ) : hasContent && editor ? (
            <div className="flex min-h-0 flex-1 flex-col overflow-hidden">
              {/* Formatting bar */}
              <div className="flex shrink-0 items-center gap-0.5 border-b bg-muted/30 px-3 py-1">
                <ToolbarBtn
                  icon={Bold}
                  active={editor.isActive("bold")}
                  onClick={() => editor.chain().focus().toggleBold().run()}
                  title="Bold"
                />
                <ToolbarBtn
                  icon={Italic}
                  active={editor.isActive("italic")}
                  onClick={() => editor.chain().focus().toggleItalic().run()}
                  title="Italic"
                />
                <div className="mx-1 h-4 w-px bg-border" />
                <ToolbarBtn
                  icon={Heading1}
                  active={editor.isActive("heading", { level: 1 })}
                  onClick={() =>
                    editor.chain().focus().toggleHeading({ level: 1 }).run()
                  }
                  title="Heading 1"
                />
                <ToolbarBtn
                  icon={Heading2}
                  active={editor.isActive("heading", { level: 2 })}
                  onClick={() =>
                    editor.chain().focus().toggleHeading({ level: 2 }).run()
                  }
                  title="Heading 2"
                />
                <ToolbarBtn
                  icon={Heading3}
                  active={editor.isActive("heading", { level: 3 })}
                  onClick={() =>
                    editor.chain().focus().toggleHeading({ level: 3 }).run()
                  }
                  title="Heading 3"
                />
                <div className="mx-1 h-4 w-px bg-border" />
                <ToolbarBtn
                  icon={List}
                  active={editor.isActive("bulletList")}
                  onClick={() =>
                    editor.chain().focus().toggleBulletList().run()
                  }
                  title="Bullet list"
                />
                <ToolbarBtn
                  icon={ListOrdered}
                  active={editor.isActive("orderedList")}
                  onClick={() =>
                    editor.chain().focus().toggleOrderedList().run()
                  }
                  title="Numbered list"
                />
                <div className="mx-1 h-4 w-px bg-border" />
                <ToolbarBtn
                  icon={Undo2}
                  active={false}
                  onClick={() => editor.chain().focus().undo().run()}
                  title="Undo"
                />
                <ToolbarBtn
                  icon={Redo2}
                  active={false}
                  onClick={() => editor.chain().focus().redo().run()}
                  title="Redo"
                />
                <div className="flex-1" />
                <span className="text-[11px] tabular-nums text-muted-foreground">
                  {wordCount} words
                </span>
              </div>

              {/* Editor content (scrolls) */}
              <div
                ref={editorScrollRef}
                className="min-h-0 flex-1 overflow-y-auto px-6 py-4"
              >
                <div className="mx-auto max-w-3xl">
                  <EditorContent editor={editor} />
                </div>
              </div>
            </div>
          ) : (
            <div className="flex flex-1 flex-col items-center justify-center gap-4 p-8">
              <div className="flex size-14 items-center justify-center rounded-xl bg-muted">
                <FileText className="size-6 text-muted-foreground" />
              </div>
              <div className="text-center">
                <h3 className="text-sm font-semibold">No content yet</h3>
                <p className="mt-1 text-xs text-muted-foreground">
                  Generate the technical proposal to get started.
                </p>
              </div>
              <Button
                variant="default"
                size="sm"
                onClick={handleGenerate}
                disabled={isStreaming}
              >
                <Sparkles />
                Generate Chapter 3
              </Button>
            </div>
          )}
        </div>

        {/* Right: Adjust Panel (stays still) */}
        <div className="flex w-[340px] shrink-0 flex-col overflow-hidden bg-muted/20">
          <div className="flex items-center justify-between border-b px-4 py-2">
            <div className="flex items-center gap-2">
              <MessageSquare className="size-3.5 text-muted-foreground" />
              <span className="text-xs font-semibold">Adjust & Refine</span>
            </div>
            {promptHistory.length > 0 && (
              <Button
                variant="ghost"
                size="icon-xs"
                onClick={() => setPromptHistory([])}
                title="Clear history"
              >
                <X className="size-3" />
              </Button>
            )}
          </div>

          <div
            ref={panelScrollRef}
            className="flex-1 overflow-y-auto px-4 py-3"
          >
            {promptHistory.length === 0 && !hasContent ? (
              <div className="flex h-full flex-col items-center justify-center text-center">
                <p className="text-xs leading-relaxed text-muted-foreground">
                  Generate content first, then use this panel to adjust and
                  refine with natural language instructions.
                </p>
              </div>
            ) : (
              <div className="flex flex-col gap-2">
                {promptHistory.map((entry, i) => (
                  <div
                    key={i}
                    className={`rounded-lg px-3 py-2 text-xs leading-relaxed ${
                      entry.role === "user"
                        ? "bg-primary/10 text-foreground"
                        : "bg-muted text-muted-foreground"
                    }`}
                  >
                    {entry.role === "user" ? (
                      <span className="font-medium">{entry.text}</span>
                    ) : (
                      <span>{entry.text}</span>
                    )}
                  </div>
                ))}
                {isStreaming && (
                  <div className="flex items-center gap-2 rounded-lg bg-muted px-3 py-2">
                    <Loader2 className="size-3 animate-spin text-muted-foreground" />
                    <span className="text-xs text-muted-foreground">
                      Processing...
                    </span>
                  </div>
                )}
              </div>
            )}
          </div>

          <div className="shrink-0 border-t bg-background p-3">
            <div className="flex gap-2">
              <Textarea
                value={adjustContext}
                onChange={(e) => setAdjustContext(e.target.value)}
                placeholder={
                  hasContent
                    ? "e.g. Make security section more detailed..."
                    : "Generate content first..."
                }
                disabled={!hasContent || isStreaming}
                className="min-h-[56px] flex-1 resize-none border-input/60 bg-background text-xs"
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault();
                    handleAdjust();
                  }
                }}
              />
              <Button
                variant="default"
                size="icon"
                onClick={handleAdjust}
                disabled={!hasContent || isStreaming || !adjustContext.trim()}
                className="size-9 shrink-0 self-end"
              >
                <Send className="size-3.5" />
              </Button>
            </div>
            <p className="mt-1.5 text-[10px] text-muted-foreground">
              Press{" "}
              <kbd className="rounded border px-1 font-mono text-[10px]">
                Enter
              </kbd>{" "}
              to send,{" "}
              <kbd className="rounded border px-1 font-mono text-[10px]">
                Shift+Enter
              </kbd>{" "}
              for new line
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

function ToolbarBtn({
  icon: Icon,
  active,
  onClick,
  title,
}: {
  icon: React.ComponentType<{ className?: string }>;
  active: boolean;
  onClick: () => void;
  title: string;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      title={title}
      className={`flex size-6 items-center justify-center rounded transition-colors ${
        active
          ? "bg-accent text-accent-foreground"
          : "text-muted-foreground hover:bg-accent/50 hover:text-foreground"
      }`}
    >
      <Icon className="size-3.5" />
    </button>
  );
}
