"use client";

import { Suspense, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { ArrowRight, Search } from "lucide-react";

import { RelativeTime } from "@/components/shared/RelativeTime";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { UserPill } from "@/components/shared/UserPill";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { listRfiDocuments, type RFIProjectResponse } from "@/services/rfi.service";

function DocumentSearchContent() {
  const searchParams = useSearchParams();
  const initialQuery = searchParams.get("q") || "";
  const [query, setQuery] = useState(initialQuery);
  const [documents, setDocuments] = useState<RFIProjectResponse[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    async function load() {
      try {
        setDocuments(await listRfiDocuments());
      } finally {
        setIsLoading(false);
      }
    }
    load();
  }, []);

  const results = useMemo(() => {
    const needle = query.trim().toLowerCase();
    if (!needle) return documents;
    return documents.filter((doc) => doc.fileName.toLowerCase().includes(needle));
  }, [documents, query]);

  return (
    <div className="flex-1 space-y-6 px-6 py-6">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="text-3xl font-semibold tracking-tight">Search Documents</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Search results are matched by document name only.
          </p>
        </div>
        <Link href="/documents">
          <Button variant="outline">Back to Documents</Button>
        </Link>
      </div>

      <Card className="border-border/70 shadow-sm">
        <CardContent className="space-y-4 p-4">
          <form
            action="/documents/search"
            className="relative max-w-xl"
          >
            <Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              name="q"
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              placeholder="Type document name..."
              className="pl-9"
            />
          </form>

          {isLoading ? (
            <p className="p-8 text-center text-sm text-muted-foreground">Searching documents...</p>
          ) : results.length === 0 ? (
            <div className="rounded-xl border border-dashed p-8 text-center">
              <p className="font-medium">No documents found</p>
              <p className="mt-1 text-sm text-muted-foreground">
                Try another document name.
              </p>
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Document Name</TableHead>
                  <TableHead>Generated By</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Last Modified</TableHead>
                  <TableHead className="text-right">Details</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {results.map((doc) => (
                  <TableRow key={doc.documentId}>
                    <TableCell className="font-medium">
                      <Link href={`/rfi/${doc.documentId}`} className="hover:underline">
                        {doc.fileName}
                      </Link>
                    </TableCell>
                    <TableCell>
                      <UserPill name={doc.uploaded_by?.name} email={doc.uploaded_by?.email} />
                    </TableCell>
                    <TableCell>
                      <StatusBadge status={doc.status} />
                    </TableCell>
                    <TableCell>
                      <RelativeTime
                        iso={doc.updated_at || doc.created_at}
                        className="text-muted-foreground"
                      />
                    </TableCell>
                    <TableCell className="text-right">
                      <Link href={`/rfi/${doc.documentId}`}>
                        <Button size="sm" variant="outline">
                          Open Details
                          <ArrowRight className="size-4" />
                        </Button>
                      </Link>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

export default function DocumentSearchPage() {
  return (
    <Suspense fallback={<div className="p-8 text-center text-sm text-muted-foreground">Loading...</div>}>
      <DocumentSearchContent />
    </Suspense>
  );
}
